name: CI Demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Hello CI/CD"
